[package]
name = "robby"
version = "0.1.0"
authors = ["Chris Gregory <christopher.b.gregory@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
rand = "0.8.0"
rand_pcg = "0.3.0"
